### ISSUE TITLE
Fix for crash if BUCKETS changed

### ISSUE THREAD

**Issue by rpopescu** [btorpey/clocks#2]
The code does a bit-wise AND with 255 of the iteration step to find the location where to store the sample; this obviously only works if the number of buckets is 255, and usually leads to crazy results or crashes otherwise.
The fix is trivial - do a modulo operation instead. Code diff below:

```
diff --git a/ClockBench.cpp b/ClockBench.cpp
index 8b73921..680e641 100755
--- a/ClockBench.cpp
+++ b/ClockBench.cpp
@@ -168,7 +168,7 @@ int main(int argc, char** argv)

    {
       for (int i = 0; i < ITERS * BUCKETS; ++i) {
-         int n = i & 0xff;
+         int n = i % BUCKETS;
          timestamp[n] = cpuid_rdtsc();
       }
       for (int i = 0; i < BUCKETS; ++i) {
@@ -183,7 +183,7 @@ int main(int argc, char** argv)
    #ifdef RDTSCP
    {
       for (int i = 0; i < ITERS * BUCKETS; ++i) {
-         int n = i & 0xff;
+         int n = i % BUCKETS;
          timestamp[n] = rdtscp();
       }
       for (int i = 0; i < BUCKETS; ++i) {
@@ -193,11 +193,11 @@ int main(int argc, char** argv)
       x.print();
       x.dump(file);
    }
-   #endif
+  #endif

    {
       for (int i = 0; i < ITERS * BUCKETS; ++i) {
-         int n = i & 0xff;
+         int n = i % BUCKETS;
          timestamp[n] = rdtsc();
       }
       for (int i = 0; i < BUCKETS; ++i) {
```

**Comment by btorpey** [comment]
Sorry for taking so long to get back to you!  

I avoided modulo deliberately since it can be expensive (it’s a divide, after all), and hacked the values so they would work together.  

Having said that, if you need/want to use a different # of buckets, then you prob also need to use modulo as well.  

I’ll add a comment to the source file pointing this out.  Thanks for bringing it up!

Regards,

Bill
